sentence = input("Enter a sentence: \n")
wordcount = sentence.split(" ")
print(f"The number of words are {len(wordcount)}")
lettera = sentence.lower().count("a")
print(f"There are {lettera} letter a")